name: main
on: [push]
jobs:
  print-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print text from index.js
        run: cat dist/index.js
